auto: true
pygments: true
permalink: /blog/:year-:month-:day/:title
markdown: maruku

ga_id: UA-10349264-2
disqus_shortname: eatnumber1
domain: rus.har.mn
#disqus_developer: 1
latitude_id: 4048757213362106746
github_username: eatnumber1
birthdate: August 9, 1988
twitter_username: eatnumber1

maruku:
    use_divs: true
    use_tex: true
    png_engine: blahtex
    png_dir: images/latex/
    png_url: /images/latex/

description: The personal website and blog of Russell Harmon
